// flow-typed signature: bfc602f3430b95e5fd6f35fb32cfaa23
// flow-typed version: <<STUB>>/@discovermedia/eslint-config-react_v2.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@discovermedia/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@discovermedia/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@discovermedia/eslint-config-react/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@discovermedia/eslint-config-react/index' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-react'>;
}
declare module '@discovermedia/eslint-config-react/index.js' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-react'>;
}
declare module '@discovermedia/eslint-config-react/rules.js' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-react/rules'>;
}
