// flow-typed signature: 8e9c53369ca0dfebd911438b99a13e28
// flow-typed version: <<STUB>>/@discovermedia/eslint-config-flow_v2.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@discovermedia/eslint-config-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@discovermedia/eslint-config-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@discovermedia/eslint-config-flow/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@discovermedia/eslint-config-flow/index' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-flow'>;
}
declare module '@discovermedia/eslint-config-flow/index.js' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-flow'>;
}
declare module '@discovermedia/eslint-config-flow/rules.js' {
  declare module.exports: $Exports<'@discovermedia/eslint-config-flow/rules'>;
}
